### ISSUE TITLE
Use nestjs-prisma

### ISSUE THREAD

**Issue by iddan** [wSedlacek/prisma-generators#1]
Use `PrismaModule` and `PrismaSchema` from https://github.com/marcjulian/nestjs-prisma to provide Prisma client

**Comment by wSedlacek** [comment]
🤔 this just so you can use the schematics?
Because you totally could use those schematics while still having the prisma get injected via the context. (By injecting your prisma service into your GraphQLModule factory)

By having prisma injected via the context it gives users more options on how to provide prisma. Such as just making a new PrismaClient in the GraphQLModule.

All though I was thinking about adding generated data loaders for the FieldResolvers to solve the N+1 problem which may work better with a PrismaService but I can probably get away with using context by scoping the data loader to the context (which it more or less is scoped to the request anyways)

**Comment by iddan** [comment]
I was not referring to the schematics option. Since the latest version, the package exposes PrismaService and PrismaModule that just provide an injectable PrismaClient instance which as far as I understand is best practice in Nest.js.

**Comment by wSedlacek** [comment]
> I was not referring to the schematics option. Since the latest version, the package exposes PrismaService and PrismaModule that just provide an injectable PrismaClient instance which as far as I understand is best practice in Nest.js.

As I mentioned you could use such a service/module as is.
Quite easily in fact.

Example
`graphql.module.ts`
```ts
import { Module } from '@nestjs/common';
import { GraphQLModule as GqlModule } from '@nestjs/graphql';

import { GraphQLOptions } from './graphql.options';

// import PrismaModule

@Module({
  imports: [
    PrismaModule,
    GqlModule.forRootAsync({ useClass: GraphQLOptions })
  ],
})
export class GraphQLModule {}
```

`graphql.options.ts`
```ts
import { Injectable } from '@nestjs/common';
import { GqlModuleOptions, GqlOptionsFactory } from '@nestjs/graphql';

// import PrismaService

@Injectable()
export class GraphQLOptions implements GqlOptionsFactory {
  constructor(
    private readonly prisma: PrismaService,
  ) {}

  public async createGqlOptions(): Promise<GqlModuleOptions> {
    return {
      context: () => ({ prisma: this.prisma }),
      <other-options>
    };
  }
}
```
Note that depending on if `PrismaModule` is `@Global()` or not you may need to adjust how your import it.

Is anything further then this really needed?

**Comment by iddan** [comment]
That is cool, thank you for taking the time to give a detailed example. I think it can be good to use the nestjs-prisma module by default but it's up to you. As long as I can integrate it myself I'm happy.

**Comment by wSedlacek** [comment]
> That is cool, thank you for taking the time to give a detailed example. I think it can be good to use the nestjs-prisma module by default but it's up to you. As long as I can integrate it myself I'm happy.

The problem is flexibility. I don't want to tie myself to `nestjs-prisma` itself as I am not confident in the level of support it will receive in the future as it is no first party to NestJS nor to Prisma. Prisma has changed several times in the past few months and it need highly dedicated maintainers to keep up. Additionally making my own Module and Service is out of the scope of this project.

Using Context lets users inject their own Prisma instance without needing to worry about what module their Prisma provider is in or if they even have one. I think for now this is the best decision. Maybe when Prisma stabilizes or when `nestjs-prisma` has been going a good 6 months or so I can reevaluate the situation.
